language: go

matrix:
  include:
    - go: 1.9.x
      env: GO111MODULE=on
    - go: 1.x
      env: GO111MODULE=on LATEST=true COVER='-coverprofile=coverage.txt -covermode=atomic'

script:
  - cd v2; go test -race $COVER ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: rm ../go.mod; curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $LATEST = true
