language: go

matrix:
  include:
    - go: 1.9.x
      env: GO111MODULE=on
    - go: 1.12.x
      env: GO111MODULE=on COVER='-coverprofile=coverage.txt -covermode=atomic'

install:
  - go get -t -v ./...

script:
  - go test -race $COVER ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
